#!/bin/sh

PREREQ="udev"
prereqs() { echo "$PREREQ"; }
case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

# Runs after udev, before the root filesystem is mounted.
exec </dev/console >/dev/console 2>&1
/bin/slots-boot
